Oficina/Controllers/MarcacoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Oficina.Helpers;
using Oficina.Models;
using Oficina.ViewModels;

namespace Oficina.Controllers
{
    [Authorize(Users = "luis@mail.pt")]
    public class MarcacoesController : Controller
    {

        private OficinaContext db = new OficinaContext();

        // GET: Marcacoes
        public ActionResult NovaReparacao()
        {

            var reparacaoView = new ReparacaoViewModels();
            reparacaoView.Viatura = new Viatura();
            reparacaoView.Mecanico = new Mecanico();
            reparacaoView.Pecas = new List<PecaReparacao>();

            Session["reparacaoView"] = reparacaoView;


            ViewBag.IdViatura = new SelectList(CombosHelper.GetViaturas().
                OrderBy(x => x.ClienteNome), "IdViatura", "ClienteNome");

            ViewBag.IdMecanico = new SelectList(CombosHelper.GetMecanicos().
                OrderBy(x => x.NomeMecanico), "IdMecanico", "NomeMecanico");


            return View(reparacaoView);
        }



        [HttpPost]
        public ActionResult NovaReparacao(ReparacaoViewModels reparacaoView)
        {
            reparacaoView = Session["reparacaoView"] as ReparacaoViewModels;

            var idViatura = int.Parse(Request["IdViatura"]);
            var data = DateTime.Parse(Request["Data"]);
            var idMecanico = int.Parse(Request["IdMecanico"]);

            if (idViatura == 0)
            {
                ViewBag.IdViatura = new SelectList(CombosHelper.GetViaturas().
                    OrderBy(x => x.ClienteNome), "IdViatura", "ClienteNome");

                ViewBag.IdMecanico = new SelectList(CombosHelper.GetMecanicos().
                    OrderBy(x => x.NomeMecanico), "IdMecanico", "NomeMecanico");

                ViewBag.Error = "Deve selecionar o cliente";

                return View(reparacaoView);
            }

            if (idMecanico == 0)
            {
                ViewBag.IdViatura = new SelectList(CombosHelper.GetViaturas().
                    OrderBy(x => x.ClienteNome), "IdViatura", "ClienteNome");

                ViewBag.IdMecanico = new SelectList(CombosHelper.GetMecanicos().
                    OrderBy(x => x.NomeMecanico), "IdMecanico", "NomeMecanico");

                ViewBag.Error = "Deve selecionar o mecânico";

                return View(reparacaoView);
            }

            var viatura = db.Viaturas.Find(idViatura);

            if (viatura == null)
            {
                ViewBag.IdViatura = new SelectList(CombosHelper.GetViaturas().
                    OrderBy(x => x.ClienteNome), "IdViatura", "ClienteNome");

                ViewBag.IdMecanico = new SelectList(CombosHelper.GetMecanicos().
                    OrderBy(x => x.NomeMecanico), "IdMecanico", "NomeMecanico");

                ViewBag.Error = "O cliente não existe";

                return View(reparacaoView);
            }

            var mecanico = db.Viaturas.Find(idViatura);

            if (mecanico == null)
            {
                ViewBag.IdViatura = new SelectList(CombosHelper.GetViaturas().
                    OrderBy(x => x.ClienteNome), "IdViatura", "ClienteNome");

                ViewBag.IdMecanico = new SelectList(CombosHelper.GetMecanicos().
                    OrderBy(x => x.NomeMecanico), "IdMecanico", "NomeMecanico");

                ViewBag.Error = "O mecanico não existe";

                return View(reparacaoView);
            }

            if (reparacaoView.Pecas.Count == 0)
            {
                ViewBag.IdViatura = new SelectList(CombosHelper.GetViaturas().
                    OrderBy(x => x.ClienteNome), "IdViatura", "ClienteNome");

                ViewBag.IdMecanico = new SelectList(CombosHelper.GetMecanicos().
                    OrderBy(x => x.NomeMecanico), "IdMecanico", "NomeMecanico");

                ViewBag.Error = "Deve escolher as peças a encomendar";

                return View(reparacaoView);
            }

            int idReparacao = 0;

            using (var transaction = db.Database.BeginTransaction())
            {
                try
                {
                    var reparacao = new Reparacao
                    {
                        IdViatura = idViatura,
                        DataInicio = data,
                        Status = Status.Activa,
                        Descricao = "...",
                        IdMecanico = idMecanico
                    };

                    db.Reparacaos.Add(reparacao);
                    db.SaveChanges();

                    idReparacao = reparacao.IdReparacao;


                    foreach (var item in reparacaoView.Pecas)
                    {
                        var reparacaoDetalhe = new ReparacaoDetalhe
                        {
                            IdReparacao = idReparacao,
                            IdPeca = item.IdPeca,
                            Quantidade = item.Quantidade
                        };

                        db.ReparacaoDetalhes.Add(reparacaoDetalhe);
                        db.SaveChanges();

                    }

                    transaction.Commit();
                }
                catch (Exception ex)
                {
                    transaction.Rollback();
                    ViewBag.Error = $"Erro: {ex}";

                    ViewBag.IdViatura = new SelectList(CombosHelper.GetViaturas().
                        OrderBy(x => x.ClienteNome), "IdViatura", "ClienteNome");

                    ViewBag.IdMecanico = new SelectList(CombosHelper.GetMecanicos().
                        OrderBy(x => x.NomeMecanico), "IdMecanico", "NomeMecanico");

                    return View(reparacaoView);
                }
            }



            ViewBag.Message = $"A reparação nº. {idReparacao} foi marcada com sucesso!";

            ViewBag.IdViatura = new SelectList(CombosHelper.GetViaturas().
                OrderBy(x => x.ClienteNome), "IdViatura", "ClienteNome");

            ViewBag.IdMecanico = new SelectList(CombosHelper.GetMecanicos().
                OrderBy(x => x.NomeMecanico), "IdMecanico", "NomeMecanico");


            reparacaoView = new ReparacaoViewModels();
            reparacaoView.Viatura = new Viatura();
            reparacaoView.Pecas = new List<PecaReparacao>();

            Session["reparacaoView"] = reparacaoView;

            return View(reparacaoView);
            //return RedirectToAction("NovaReparacao");
        }




        public ActionResult AdicionaPeca()
        {

            ViewBag.IdPeca = new SelectList(CombosHelper.GetPecas(), "IdPeca", "Descricao");

            return View();
        }


        [HttpPost]
        public ActionResult AdicionaPeca(PecaReparacao pecaReparacao) 
        {
            var reparacaoView = Session["reparacaoView"] as ReparacaoViewModels;


            var idPeca = int.Parse(Request["IdPeca"]);

            if (idPeca == 0)
            {
                ViewBag.IdPeca = new SelectList(CombosHelper.GetPecas(), "IdPeca", "Descricao");
                ViewBag.Error = "Deve selecionar uma peça";

                return View(pecaReparacao);
            }


            var quantidade = Request["Quantidade"];

            if ( string.IsNullOrEmpty(quantidade))
            {
                ViewBag.IdPeca = new SelectList(CombosHelper.GetPecas(), "IdPeca", "Descricao");
                return View(pecaReparacao);
            }
            if (int.Parse(quantidade) <= 0)
            {
                ViewBag.IdPeca = new SelectList(CombosHelper.GetPecas(), "IdPeca", "Descricao");
                //ViewBag.Error = "Deve inserir uma quantidade superior a zero";

                return View(pecaReparacao);
            }


            var peca = db.Pecas.Find(idPeca);

            if (peca == null)
            {
                ViewBag.IdPeca = new SelectList(CombosHelper.GetPecas(), "IdPeca", "Descricao");
                ViewBag.Error = "A peça não existe";

                return View(pecaReparacao);
            }

            pecaReparacao = reparacaoView.Pecas.Find(p => p.IdPeca == idPeca);

            if (pecaReparacao == null)
            {
                pecaReparacao = new PecaReparacao
                {
                    Descricao = peca.Descricao,
                    Preco = peca.Preco,
                    IdPeca = peca.IdPeca,
                    Quantidade = int.Parse(Request["Quantidade"])

                };

                reparacaoView.Pecas.Add(pecaReparacao);
            }
            else
            {
                pecaReparacao.Quantidade += int.Parse(Request["Quantidade"]);
            }



            ViewBag.IdViatura = new SelectList(CombosHelper.GetViaturas().
                OrderBy(x => x.ClienteNome), "IdViatura", "ClienteNome");

            ViewBag.IdMecanico = new SelectList(CombosHelper.GetMecanicos().
                OrderBy(x => x.NomeMecanico), "IdMecanico", "NomeMecanico");


            return View("NovaReparacao", reparacaoView);

        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Oficina/Views/Marcacoes/AdicionaPeca.cshtml
@using Oficina.ViewModels
@model Oficina.Models.PecaReparacao

@{
    ViewBag.Title = "Adiciona Peça";
}

<h2>Adicionar Peça</h2>

<h4 class="text-danger">@ViewBag.Error</h4>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdPeca, "Peça", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdPeca", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdPeca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Adicionar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "NovaReparacao", "Marcacoes", HttpContext.Current.Session["reparacaoView"])
</div>

Oficina/Views/Marcacoes/NovaReparacao.cshtml
@model Oficina.ViewModels.ReparacaoViewModels

@{
    /**/

    ViewBag.Title = "Nova Reparação";
}

<h2>Nova Reparação</h2>

<h4 class="text-success">@ViewBag.Message</h4>
<h4 class="text-danger">@ViewBag.Error</h4>

@using (Html.BeginForm("NovaReparacao", "Marcacoes", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">


        <div class="form-group">
            @Html.LabelFor(model => model.Viatura.IdViatura, "Cliente", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdViatura", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Viatura.IdViatura, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Data, new { type = "datetime-local", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Mecanico.IdMecanico, "Mecânico", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdMecanico", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Mecanico.IdMecanico, "", new { @class = "text-danger" })
            </div>
        </div>
        <br /> <br />

        @Html.ActionLink("Adicionar Peça", "AdicionaPeca", new { }, new { @class = "btn btn-primary" })


        <input type="submit" value="Marcar Reparação" id="NewOrder" class="btn btn-success" />

    </div>
    <br /> <br />

    <h3>Peças</h3>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Peca.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Peca.Preco)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Peca.Quantidade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Peca.Valor)
            </th>
            <th></th>
        </tr>

        @for (int i = 0; i < Model.Pecas.Count; i++)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => Model.Pecas[i].Descricao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.Pecas[i].Preco)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.Pecas[i].Quantidade)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.Pecas[i].Valor)
                </td>
                <td>

                    @*@Html.ActionLink("Edit", "Edit", new { id = Model.Pecas[i].IdPeca }) |
                        @Html.ActionLink("Delete", "Delete", new { id = Model.Pecas[i].IdPeca })*@
                </td>
            </tr>
        }

    </table>
}
<br/><br />
@Html.ActionLink("Lista de Reparações", "Index", "Reparacaos")