Oficina/Models/Peca.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Dynamic;
using System.Linq;
using System.Web;

namespace Oficina.Models
{
    public class Peca
    {
        [Key]
        public int IdPeca { get; set; }

        [Display(Name = "Descrição")]
        [StringLength(30, ErrorMessage = "A {0} devera ter entre {2} e {1} carateres", MinimumLength = 3)]
        [Required(ErrorMessage = "Deve inserir uma {0}")]
        public string Descricao { get; set; }

        [DataType(DataType.Currency)]
        [DisplayFormat(DataFormatString = "{0:C2}", ApplyFormatInEditMode = false)]
        [Display(Name = "Preço (c/ IVA)")]
        [Required(ErrorMessage = "Deve inserir um {0}")]
        public decimal Preco { get; set; }
        
        public string Imagem { get; set; }

        [NotMapped]
        public HttpPostedFileBase PecaImagemURL { get; set; }




        public virtual ICollection<ReparacaoDetalhe> ReparacaoDetalhes { get; set; }
    }


}

Oficina/Controllers/PecasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using Oficina.Helpers;
using Oficina.Models;

namespace Oficina.Controllers
{
    public class PecasController : Controller
    {
        private OficinaContext db = new OficinaContext();

        
        // GET: Pecas
        //[Authorize(Roles="View")]
        public ActionResult Index()
        {
            ViewBag.Contagem = db.Pecas.Count();
            return View(db.Pecas.ToList());
        }


        // GET: Pecas/Details/5
        [Authorize(Roles = "View")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Peca peca = db.Pecas.Find(id);
            if (peca == null)
            {
                return HttpNotFound();
            }

            return View(peca);
        }

        // GET: Pecas/Create
        [Authorize(Roles = "Create")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pecas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdPeca,Descricao,Preco,Imagem,PecaImagemURL")] Peca peca)
        {
            if (ModelState.IsValid)
            {
                db.Pecas.Add(peca);
                db.SaveChanges();

                if (peca.PecaImagemURL != null)
                {
                    var pasta = "~/Content/Images";
                    var ficheiro = string.Format("{0}.jpg", peca.IdPeca);

                    var resposta = FilesHelper.UploadImagem(peca.PecaImagemURL, pasta, ficheiro);

                    if (resposta)
                    {
                        var pic = string.Format("{0}/{1}", pasta, ficheiro);
                        peca.Imagem = pic;
                        db.Entry(peca).State = EntityState.Modified;
                        db.SaveChanges();
                    }
                }

                return RedirectToAction("Index");
            }

            return View(peca);
        }


        // GET: Pecas/Edit/5
        [Authorize(Roles = "Edit")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Peca peca = db.Pecas.Find(id);
            if (peca == null)
            {
                return HttpNotFound();
            }
            return View(peca);
        }

        // POST: Pecas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdPeca,Descricao,Preco,Imagem,PecaImagemURL")] Peca peca)
        {
            if (ModelState.IsValid)
            {
                if (peca.PecaImagemURL != null)
                {
                    var pic = string.Empty;
                    var pasta = "~/Content/Images";
                    var ficheiro = string.Format("{0}.jpg", peca.IdPeca);

                    var response = FilesHelper.UploadImagem(peca.PecaImagemURL, pasta, ficheiro);

                    if (response)
                    {
                        pic = string.Format("{0}/{1}", pasta, ficheiro);
                        peca.Imagem = pic;

                    }
                }

                db.Entry(peca).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(peca);
        }


        // GET: Pecas/Delete/5
        [Authorize(Roles = "Delete")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Peca peca = db.Pecas.Find(id);
            if (peca == null)
            {
                return HttpNotFound();
            }
            return View(peca);
        }

        // POST: Pecas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Peca peca = db.Pecas.Find(id);
            db.Pecas.Remove(peca);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Oficina/Views/Pecas/Create.cshtml
@model Oficina.Models.Peca

@{
    ViewBag.Title = "Criar";
}

<h2>Criar</h2>


@using (Html.BeginForm("Create", "Pecas", FormMethod.Post, new { encType = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Peça</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PecaImagemURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                    @Html.TextBoxFor(model => model.PecaImagemURL, new { type = "file" })
                </span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script src="~/Scripts/globalize.js"></script>
    <script src="~/Scripts/globalize/cultures/globalize.culture.@(System.Threading.Thread.CurrentThread.CurrentCulture.Name).js"></script>
    <script>
        $.validator.methods.number = function(value, element) {

            return this.options(element) || !isNaN(Globalize.parseFloat(value));
        }
        $(document).ready(function() {
            Globalize.culture('@(System.Threading.Thread.CurrentThread.CurrentCulture.Name)');

        });
    </script>

    <script>
        JQuery.extend(JQuery.validator.methods,
            {
                range: function(value, element, param) {

                    var val = Globalize.parseFloat(value);
                    return this.optional(element) ||
                    (
                        val >= param[0] && val <= param[1]);
                }
            });

        $.validator.methods.date = function(value, element) {

            return this.optional(element) ||
                Globalize.parseDate(value) ||
                Globalize.parseDate(value, "dd-MM-yyyy");
        }

    </script>
}

Oficina/Views/Pecas/Delete.cshtml
@model Oficina.Models.Peca

@{
    ViewBag.Title = "Apagar";
}

<h2>Apagar</h2>

<h3>Tem a certeza que pretende apagar?</h3>
<div>
    <h4>Peça</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Preco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Preco)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Apagar" class="btn btn-default" /> |
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>

Oficina/Views/Pecas/Details.cshtml
@model Oficina.Models.Peca

@{
    ViewBag.Title = "Detalhes";
}

<h2>Detalhes</h2>



<div>

    <h4>Peça</h4>

    <hr/>
    <div>
        <img src="@Url.Content(Html.DisplayFor(model => model.Imagem).ToString())" 
             alt="Imagem" style="width: 200px; height: 200px; max-width: 100%; height:auto"/>
    </div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Preco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Preco)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.IdPeca }) |
    @Html.ActionLink("Voltar", "Index")
</p>

Oficina/Views/Pecas/Edit.cshtml
@model Oficina.Models.Peca

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm("Edit", "Pecas", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Peça</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdPeca)

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PecaImagemURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                    @Html.TextBoxFor(model => model.PecaImagemURL, new { type = "file" })
                </span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script src="~/Scripts/globalize.js"></script>
    <script src="~/Scripts/globalize/cultures/globalize.culture.@(System.Threading.Thread.CurrentThread.CurrentCulture.Name).js"></script>
    <script>
        $.validator.methods.number = function(value, element) {

            return this.options(element) || !isNaN(Globalize.parseFloat(value));
        }
        $(document).ready(function() {
            Globalize.culture('@(System.Threading.Thread.CurrentThread.CurrentCulture.Name)');

        });
    </script>

    <script>
        JQuery.extend(JQuery.validator.methods,
            {
                range: function(value, element, param) {

                    var val = Globalize.parseFloat(value);
                    return this.optional(element) ||
                    (
                        val >= param[0] && val <= param[1]);
                }
            });

        $.validator.methods.date = function(value, element) {

            return this.optional(element) ||
                Globalize.parseDate(value) ||
                Globalize.parseDate(value, "dd-MM-yyyy");
        }

    </script>
}

Oficina/Views/Pecas/Index.cshtml
@model IEnumerable<Oficina.Models.Peca>

@{
    ViewBag.Title = "Peças";
}

<h2 style="text-align:left;float:left">Peças</h2>
<h4 style="text-align:right; float: right">resultado(@ViewBag.Contagem)</h4>
<p style="clear: both">
    @Html.ActionLink("Criar Novo", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Preco)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Preco)
            </td>
            <td>
                @if (!string.IsNullOrEmpty(item.Imagem))
                {
                    <img src="@Url.Content(item.Imagem)" alt="Imagem" style="width: 50px; height: 50px; max-width: 100%; height:auto" />
                }
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.IdPeca }) |
                @Html.ActionLink("Detalhes", "Details", new { id = item.IdPeca }) |
                @Html.ActionLink("Apagar", "Delete", new { id = item.IdPeca })
            </td>
        </tr>
    }

</table>