Oficina/Models/Reparacao.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Http.Results;
using Oficina.Models;

namespace Oficina.Models
{

    public class Reparacao
    {

        OficinaContext db = new OficinaContext();

        [Key]
        public int IdReparacao { get; set; }

        [Display(Name = "Descricao")]
        [StringLength(35, ErrorMessage = "A {0} deve ter entre {2} e {1} carateres", MinimumLength = 3)]
        [Required(ErrorMessage = "Deve inserir uma {0}")]
        public string Descricao { get; set; }

        [Display(Name="Viatura")]
        public int IdViatura { get; set; }

        [NotMapped]
        public string Cliente
        {
            get
            {
                var cliente = db.Clientes.
                    First(c => c.IdCliente == db.Viaturas.
                    FirstOrDefault(v => v.IdViatura == IdViatura).IdCliente);
                return cliente.Nome;
            }
        }

        [DisplayName("Mecânico")]
        public int IdMecanico { get; set; }

        //[NotMapped]
        //public string MecanicoNome
        //{
        //    get
        //    {
        //        //var mecanico = db.Mecanicoes.FirstOrDefault(m => m.IdMecanico == IdMecanico);
        //        return Mecanico.Nome; //desnecessário
        //    }
        //}

        [DataType(DataType.DateTime)]
        //[DisplayFormat(DataFormatString = "dd/mm/yyyy hh:mm", ApplyFormatInEditMode = true)]
        [Display(Name = "Data Início")]
        [Required(ErrorMessage = "O campo {0} é de preenchimento obrigatório")]
        public DateTime DataInicio { get; set; }

        [DataType(DataType.DateTime)]
        //[DisplayFormat(DataFormatString = "dd/mm/yyyy hh:mm", ApplyFormatInEditMode = true)]
        [Display(Name = "Data Fim")]
        public DateTime? DataFim { get; set; }

        public Status Status { get; set; }





        public virtual Viatura Viatura { get; set; }

        public virtual Mecanico Mecanico { get; set; }

        public virtual ICollection<Fatura> Faturas { get; set; }

        public virtual ICollection<ReparacaoDetalhe> ReparacaoDetalhes { get; set; }




        public static double GetDiasUteis(DateTime dataInicio, DateTime dataFim)
        {
            var diasUteis =
                1 + ((dataFim - dataInicio).TotalDays * 5 -
                     (dataInicio.DayOfWeek - dataFim.DayOfWeek) * 2) / 7;

            if (dataFim.DayOfWeek == DayOfWeek.Saturday)
                diasUteis--;
            if (dataInicio.DayOfWeek == DayOfWeek.Sunday)
                diasUteis--;

            return diasUteis;
        }
    }

    public enum Status { Activa, Finalizada }
}

Oficina/ViewModels/ReparacaoViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Oficina.Models;

namespace Oficina.ViewModels
{
    public class ReparacaoViewModels
    {
        public Viatura Viatura { get; set; }

        [DataType(DataType.DateTime)]
        //[DisplayFormat(DataFormatString = "dd/mm/yyyy hh:mm", ApplyFormatInEditMode = true)]
        [Display(Name = "Data Início")]
        [Required(ErrorMessage = "O campo {0} é de preenchimento obrigatório")]
        public DateTime Data { get; set; }

        public Mecanico Mecanico { get; set; }

        public PecaReparacao Peca { get; set; }

        public List<PecaReparacao> Pecas { get; set; }
    }
}

Oficina/Controllers/ReparacaosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Oficina.Models;

namespace Oficina.Controllers
{
    public class ReparacaosController : Controller
    {
        private OficinaContext db = new OficinaContext();

        // GET: Reparacaos
        //[Authorize(Roles = "View")]
        public ActionResult Index(string cliente, string search, string ordenar)
        {
            
            var reparacaos = db.Reparacaos.Include(r => r.Mecanico).Include(r => r.Viatura);
            
            var reps = reparacaos;
            //var nomeClientes = reparacaos.SelectMany(r => db.Viaturas.Where(v => r.IdViatura == v.IdViatura));
            //var nomeClientes = reparacaos.Any(r => r.Cliente.Contains(search));
            var clientes = db.Clientes.Where(c => (c.PrimeiroNome + " " + c.Apelido).Contains(search));
            var reparacaosclientes = clientes.SelectMany(c => reps.Where(r => r.Viatura.IdCliente == c.IdCliente));



            if (!String.IsNullOrEmpty(search))
            {
                reparacaos = reparacaos.Where(r => r.Descricao.Contains(search) ||
                                                   r.Mecanico.Nome.Contains(search) ||
                                                   r.Viatura.Matricula.Contains(search) ||
                                                   r.Viatura.Marca.Contains(search) ||
                                                   r.Viatura.Modelo.Contains(search) ||
                                                   r.Status.ToString().Contains(search));
                ViewBag.Search = search;
            }


            var reparacaoz = reparacaosclientes.Union(reparacaos);


            var clients = reparacaoz.OrderBy(r => r.Viatura.Cliente.PrimeiroNome + " " + r.Viatura.Cliente.Apelido).
                Select(r => r.Viatura.Cliente.PrimeiroNome + " " + r.Viatura.Cliente.Apelido).Distinct();

            if (!String.IsNullOrEmpty(cliente))
            {
                reparacaoz = reparacaoz.Where(r =>
                    r.Viatura.Cliente.PrimeiroNome + " " + r.Viatura.Cliente.Apelido == cliente);
            }

            ViewBag.Cliente = new SelectList(clients);

            ViewBag.Contagem = reparacaoz.Count();

            if (!string.IsNullOrEmpty(ordenar))
            {
                switch (ordenar)
                {
                    case "ascendente":
                        reparacaoz = reparacaoz.OrderBy(r => r.DataInicio);
                        break;
                    case "descendente":
                        reparacaoz = reparacaoz.OrderByDescending(r => r.DataInicio);
                        break;
                }
            }
            List<string> ordem = new List<string>(new[] { "ascendente", "descendente" });
            //var ordenarData = ordem.Where(x => !string.IsNullOrEmpty(x));
            ViewBag.Ordenar = new SelectList(ordem);

            return View(reparacaoz.ToList());
        }

        // GET: Reparacaos/Details/5
        [Authorize(Roles = "View")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Reparacao reparacao = db.Reparacaos.Find(id);

            if (reparacao == null)
            {
                return HttpNotFound();
            }
            ViewBag.Detalhes = db.ReparacaoDetalhes.Where(x => x.IdReparacao == id).ToList();

            return View(reparacao);
        }

        // GET: Reparacaos/Create
        [Authorize(Roles = "Create")]
        public ActionResult Create()
        {
            ViewBag.IdMecanico = new SelectList(db.Mecanicoes, "IdMecanico", "Nome");
            ViewBag.IdViatura = new SelectList(db.Viaturas, "IdViatura", "Matricula");
            return View();
        }

        // POST: Reparacaos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdReparacao,Descricao,IdViatura,IdMecanico,DataInicio,DataFim,Status")] Reparacao reparacao)
        {
            if (ModelState.IsValid)
            {
                db.Reparacaos.Add(reparacao);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.IdMecanico = new SelectList(db.Mecanicoes, "IdMecanico", "Nome", reparacao.IdMecanico);
            ViewBag.IdViatura = new SelectList(db.Viaturas, "IdViatura", "Matricula", reparacao.IdViatura);
            return View(reparacao);
        }

        // GET: Reparacaos/Edit/5
        [Authorize(Roles = "Edit")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reparacao reparacao = db.Reparacaos.Find(id);
            if (reparacao == null)
            {
                return HttpNotFound();
            }

            Session["inicial"] = reparacao.DataInicio;
            ViewBag.Inic = reparacao.DataInicio;

            ViewBag.IdMecanico = new SelectList(db.Mecanicoes, "IdMecanico", "Nome", reparacao.IdMecanico);
            ViewBag.IdViatura = new SelectList(db.Viaturas, "IdViatura", "Matricula", reparacao.IdViatura);
            return View(reparacao);

        }


        // POST: Reparacaos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdReparacao,Descricao,IdViatura,IdMecanico,DataInicio,DataFim,Status")] Reparacao reparacao)
        {
            reparacao.DataInicio = Convert.ToDateTime(Session["inicial"]);
            ViewBag.Inic = reparacao.DataInicio;

            if (reparacao.DataFim == null || reparacao.DataFim < reparacao.DataInicio)
            {
                ViewBag.Error = "Insira uma data de fecho da reparação não inferior à inicial";

                ViewBag.IdMecanico = new SelectList(db.Mecanicoes, "IdMecanico", "Nome", reparacao.IdMecanico);
                ViewBag.IdViatura = new SelectList(db.Viaturas, "IdViatura", "Matricula", reparacao.IdViatura);

                return View(reparacao);

            }

            var mecanico = db.Mecanicoes.First(x => x.IdMecanico == reparacao.IdMecanico);
            //var totalMaoObra = ((DateTime)reparacao.DataFim).Subtract(reparacao.DataInicio).Days * 8 *
            //                   mecanico.CustoHora;
            var datafinal = (DateTime)reparacao.DataFim;
            var totalMaoObra = (decimal)Reparacao.GetDiasUteis(reparacao.DataInicio, datafinal) * 8 *
                               mecanico.CustoHora;

            if (ModelState.IsValid)
            {
                db.Entry(reparacao).State = EntityState.Modified;
                db.SaveChanges();

                
                Fatura fatura = new Fatura
                {
                    IdReparacao = reparacao.IdReparacao,
                    DataEmissao = Convert.ToDateTime(reparacao.DataFim),
                    IdCliente = db.Viaturas.FirstOrDefault(x => x.IdViatura == reparacao.IdViatura).IdCliente,
                    //TotalMaoObra = Fatura.GetTotalMaoObra(reparacao.IdReparacao),
                    TotalMaoObra = totalMaoObra + 0.23M * totalMaoObra,
                    TotalConsumiveis = Fatura.GetTotalConsumiveis(reparacao.IdReparacao) 
                };

                if (reparacao.Status == Status.Finalizada)
                {
                    db.Faturas.Add(fatura);
                    db.SaveChanges();
                }


                //return RedirectToAction("Index");            

                ViewBag.Message = $"A reparação nº. {reparacao.IdReparacao} foi fechada com sucesso!";

                ViewBag.IdMecanico = new SelectList(db.Mecanicoes, "IdMecanico", "Nome", reparacao.IdMecanico);
                ViewBag.IdViatura = new SelectList(db.Viaturas, "IdViatura", "Matricula", reparacao.IdViatura);
                return View(reparacao);

            }


            return View(reparacao);

        }

        // GET: Reparacaos/Delete/5
        [Authorize(Roles = "Delete")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reparacao reparacao = db.Reparacaos.Find(id);
            if (reparacao == null)
            {
                return HttpNotFound();
            }
            return View(reparacao);
        }

        // POST: Reparacaos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reparacao reparacao = db.Reparacaos.Find(id);
            try
            {

                db.Reparacaos.Remove(reparacao);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                
                ViewBag.Error = "Primeiro tem de apagar os registos (detalhes e fatura) associados à reparação";
                return View();
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }



    }


}

Oficina/Views/Reparacaos/Create.cshtml
@model Oficina.Models.Reparacao

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Reparacao</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdViatura, "IdViatura", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdViatura", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdViatura, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdMecanico, "IdMecanico", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdMecanico", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdMecanico, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataInicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DataInicio, new { type = "datetime-local", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DataInicio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataFim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DataFim, new { type = "datetime-local", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DataFim, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Status, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Oficina/Views/Reparacaos/Delete.cshtml
@model Oficina.Models.Reparacao

@{
    ViewBag.Title = "Apagar";
}


<h2>Apagar</h2>

<h3>Tem a certeza que deseja apagar?</h3>
<div>
    <h4 class="text-danger">@ViewBag.Error</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Mecanico.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mecanico.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Viatura.Matricula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Viatura.Matricula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataInicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataInicio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataFim)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataFim)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Oficina/Views/Reparacaos/Details.cshtml
@model Oficina.Models.Reparacao

@{
    ViewBag.Title = "Details";
}

<h2>Detalhes</h2>

<div>
    <h4>Reparação</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Mecanico.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mecanico.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Viatura.Matricula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Viatura.Matricula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataInicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataInicio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataFim)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataFim)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>
</div>



<h3>Peças</h3>


<table class="table">
    <tr>
        <th>
            Peça
        </th>
        <th>
            Quantidade
        </th>
        <th></th>
    </tr>

    @for (int i = 0; i < ViewBag.Detalhes.Count; i++)
    {
        <tr>
            <td>
                @ViewBag.Detalhes[i].Peca.Descricao
            </td>
            <td>
                @ViewBag.Detalhes[i].Quantidade
            </td>
        </tr>
    }

</table>
<br /><br />
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.IdReparacao }) |*@
    @Html.ActionLink("Voltar", "Index")
</p>

Oficina/Views/Reparacaos/Edit.cshtml
@model Oficina.Models.Reparacao

@{
    ViewBag.Title = "Editar";
}

<h2>Finalizar reparação</h2>
<h4 class = "text-success">@ViewBag.Message</h4>
<h4 class = "text-danger">@ViewBag.Error</h4>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdReparacao)

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdViatura, "IdViatura", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdViatura", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdViatura, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdMecanico, "IdMecanico", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdMecanico", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdMecanico, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataInicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="panel panel-success">
                <div class="panel-heading">@ViewBag.Inic</div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataFim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DataFim, new { type = "datetime-local", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DataFim, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Status, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Oficina/Views/Reparacaos/Index.cshtml
@using System.Reflection.Emit
@using Oficina.Models
@model IEnumerable<Oficina.Models.Reparacao>

@{
    ViewBag.Title = "Reparações";
}

<h2 style="text-align:left;float:left">Reparações</h2>
<h4 style="text-align:right; float: right;">resultado(@ViewBag.Contagem)</h4>

<p style="clear:both">
    @*@Html.ActionLink("Create New", "Create")*@
    @using (Html.BeginForm("Index", "Reparacaos", FormMethod.Get))
    {
        <label>Ordenar por Data:</label>
        @Html.DropDownList("Ordenar", null, "default", new { @class= "form-control", style = "display:inline" })
        <input type="submit" value="Ordenar" class="btn btn-default" />

        <label>Filtrar por Cliente:</label>
        @Html.DropDownList("Cliente", null, "Todos", new { @class= "form-control", style = "display:inline" })
        <input type="submit" value="Filtrar" class="btn btn-default" />
        
        <input type="hidden" name="Search" id="Search" value="@ViewBag.Search" />

    }

</p>

<table class="table">
    <tr>
        <th>
            Mecânico
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Viatura.Matricula)
        </th>
        <th>
            Marca
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cliente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataInicio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataFim)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>

        <th></th>
    </tr>


    @foreach (var item in Model)
    {

        if (item.Status == Status.Activa)
        {

            <tr >
                <td scope="col">
                    @Html.DisplayFor(modelItem => item.Mecanico.Nome)
                </td>
                <td scope="col">
                    @Html.DisplayFor(modelItem => item.Viatura.Matricula)
                </td>
                <td scope="col">
                    @Html.DisplayFor(modelItem => item.Viatura.Marca)
                </td>
                <td scope="col">
                    @Html.DisplayFor(model => item.Cliente)
                </td>
                <td scope="col">
                    @Html.DisplayFor(modelItem => item.Descricao)
                </td>
                <td scope="col">
                    @Html.DisplayFor(modelItem => item.DataInicio)
                </td>
                <td scope="col">
                    @Html.DisplayFor(modelItem => item.DataFim)
                </td>
                <td scope="col">
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td scope="col">
                    @Html.ActionLink("Detalhes", "Details", new { id = item.IdReparacao }) |
                    @Html.ActionLink("Finalizar", "Edit", new { id = item.IdReparacao })@* |
                        @Html.ActionLink("apagar", "Delete", new { id = item.IdReparacao })*@
                </td>
            </tr>

        }
        else
        {

            <tr class="alert-success">
                <td>
                    @Html.DisplayFor(modelItem => item.Mecanico.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Viatura.Matricula)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Viatura.Marca)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Cliente)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descricao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataInicio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataFim)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @*@Html.ActionLink("Editar", "Edit", new { id = item.IdReparacao }) |
                        @Html.ActionLink("Detalhes", "Index", "ReparacaoDetalhes" ) | *@
                    @Html.ActionLink("Detalhes", "Details", new { id = item.IdReparacao }) |
                    @Html.ActionLink("Apagar", "Delete", new { id = item.IdReparacao })
                </td>
            </tr>

        }


    }

</table>