Oficina/ViewModels/RoleViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Oficina.ViewModels
{
    public class RoleViewModels
    {

        public string RoleID { get; set; }

        public string Name { get; set; }

        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        public List<RoleViewModels> Roles { get; set; }
    }
}

Oficina/ViewModels/UserViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Oficina.ViewModels
{
    public class UserViewModels
    {
        public string UserID { get; set; }

        public string Name { get; set; }

        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        public RoleViewModels Role { get; set; }

        public List<RoleViewModels> Roles { get; set; }
    }
}

Oficina/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Oficina.Helpers;
using Oficina.ViewModels;

namespace Oficina.Controllers
{
    [Authorize(Users = "luis@mail.pt")]
    public class UsersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Users
        public ActionResult Index()
        {
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            var users = userManager.Users.ToList();
            var usersView = new List<UserViewModels>();

            foreach (var user in users)
            {
                var userView = new UserViewModels
                {
                    Email = user.Email,
                    Name = user.UserName,
                    UserID = user.Id
                };

                usersView.Add(userView);
            }

            ViewBag.Contagem = usersView.Count;

            return View(usersView);
        }

        //Get Roles
        public ActionResult Roles(string userID)
        {
            if (string.IsNullOrEmpty(userID))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));

            var roles = roleManager.Roles.ToList();
            var users = userManager.Users.ToList();
            var user = users.Find(u => u.Id == userID);

            if (user == null)
            {
                return HttpNotFound();
            }

            var rolesView = new List<RoleViewModels>();

            foreach (var item in user.Roles)
            {
                var role = roles.Find(r => r.Id == item.RoleId);
                var roleview = new RoleViewModels
                {
                    RoleID = role.Id,
                    Name = role.Name
                };
                rolesView.Add(roleview);
            }

            var userView = new UserViewModels
            {
                Email = user.Email,
                Name = user.UserName,
                UserID = user.Id,
                Roles = rolesView
            };

            return View(userView);
        }


        [HttpPost]
        public ActionResult AddRole(string userID, FormCollection form)
        {
            var roleID = Request["RoleID"];

            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));

            var users = userManager.Users.ToList();
            var user = users.Find(u => u.Id == userID);

            var userView = new UserViewModels
            {
                Email = user.Email,
                Name = user.UserName,
                UserID = user.Id
            };

            if (string.IsNullOrEmpty(roleID))
            {
                ViewBag.Error = "Tem que selecionar uma permissão";
                ViewBag.RoleID = new SelectList(CombosHelper.GetRoles(), "Id", "Name");
                return View(userView);
            }
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));
            var roles = roleManager.Roles.ToList();
            var role = roles.Find(r => r.Id == roleID);

            if (!userManager.IsInRole(userID, role.Name))
            {
                userManager.AddToRole(userID, role.Name);
            }

            var rolesView = new List<RoleViewModels>();

            foreach (var item in user.Roles)
            {
                role = roles.Find(r => r.Id == item.RoleId);
                var roleView = new RoleViewModels
                {
                    Name = role.Name,
                    RoleID = role.Id
                };


                rolesView.Add(roleView);
            }

            userView = new UserViewModels()
            {
                Email = user.Email,
                Name = user.UserName,
                Roles = rolesView,
                UserID = user.Id
            };

            return View("Roles", userView);
        }

        public ActionResult AddRole(string userID)
        {
            if (string.IsNullOrEmpty(userID))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));

            var users = userManager.Users.ToList();
            var user = users.Find(u => u.Id == userID);

            if (user == null)
            {
                return HttpNotFound();
            }

            var userView = new UserViewModels
            {
                Email = user.Email,
                Name = user.UserName,
                UserID = user.Id
            };

            //var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));
            //var list = roleManager.Roles.ToList();
            //list.Add(new IdentityRole { Id = "", Name = "[Selecione uma permissão...]" });
            //list = list.OrderBy(r => r.Name).ToList();
            //ViewBag.RoleID = new SelectList(list, "Id", "Name");  //Estao no CombosHelper

            ViewBag.RoleID = new SelectList(CombosHelper.GetRoles(), "Id", "Name");

            return View(userView);
        }


        public ActionResult Delete(string userID, string roleID)
        {
            if (string.IsNullOrEmpty(userID) || string.IsNullOrEmpty(roleID))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));

            var user = userManager.Users.ToList().Find(u => u.Id == userID);
            var role = roleManager.Roles.ToList().Find(r => r.Id == roleID);

            //Apagar o user deste role
            if (userManager.IsInRole(user.Id, role.Name))
            {
                userManager.RemoveFromRole(user.Id, role.Name);
            }

            //Preparar a view
            var users = userManager.Users.ToList();
            var roles = roleManager.Roles.ToList();
            var rolesView = new List<RoleViewModels>();

            foreach (var item in user.Roles)
            {
                role = roles.Find(r => r.Id == item.RoleId);
                var roleView = new RoleViewModels
                {
                    Name = role.Name,
                    RoleID = role.Id,
                };
                rolesView.Add(roleView);

            }

            var userView = new UserViewModels
            {
                Email = user.Email,
                Name = user.UserName,
                Roles = rolesView,
                UserID = user.Id
            };

            return View("Roles", userView);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Oficina/Views/Users/AddRole.cshtml
@model Oficina.ViewModels.UserViewModels

@{
    ViewBag.Title = "AddRole";
}

<h2>Adicionar permissão para o utilizador: @Model.Name </h2>
<h3>@ViewBag.Error</h3>


@using (Html.BeginForm("AddRole", "Users", new { userID = Model.UserID }, FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <div class="form-group">
            @Html.LabelFor(model => model.Role.RoleID, "RoleID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RoleID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Role.RoleID, "", new { @class = "text-danger" })
            </div>
        </div>

        <br /><br />
        @Html.ActionLink("Voltar para utilizador", "Roles", new { userID = Model.UserID }, new { @class = "btn btn-info" })
        <input type="submit" value="Adiciona permissão" class="btn btn-success" />

    </div>

}

Oficina/Views/Users/Index.cshtml
@model IEnumerable<Oficina.ViewModels.UserViewModels>
@{
    ViewBag.Title = "Index";
}

<h2>Gestão de Permissiões</h2>
<h4>Users(@ViewBag.Contagem)</h4>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.ActionLink("Roles", "Roles", new { UserID = item.UserID })
            </td>
        </tr>
    }

</table>

Oficina/Views/Users/Roles.cshtml
@model Oficina.ViewModels.UserViewModels
@{
    ViewBag.Title = "Permissões";
}

<h2>Permissões para o utilizador: @Model.Name</h2>

<p>
    @Html.ActionLink("Adicionar Permissão", "AddRole", new { userID = Model.UserID }, new { @class = "btn btn-primary" })
    @Html.ActionLink("Voltar", "Index", new { }, new { @class = "btn btn-info" })
</p>
<table class="table">


    @for(int i = 0; i < Model.Roles.Count; i++)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => Model.Roles[i].Name)
            </td>
            <td>
                @Html.ActionLink("Apagar", "Delete", new { userID = Model.UserID, roleId = Model.Roles[i].RoleID })
            </td>

        </tr>
    }

</table>